version: '3'
services:
    js:
        build:
          context: ./JS/    
    nginx:
        build:
          context: ./Nginx/
        ports:
            - "8000:80" 
        depends_on:
            - js